### ISSUE TITLE
get-ami.sh error

### ISSUE THREAD

**Issue by xueshanf** [xuwang/aws-linux-cluster#1]
When  running make in Vagrant:

error: startswith is not defined

 | map(select(( .Name != null) and ( .Name | startswith("RHEL-7.1"))))
                                              ^^^^^^^^^^

Perhaps jq needs to be upgraded to 1.4 in Vagrant?

**Comment by xuwang** [comment]
Right, I'll upgrade the Vagrantfile to use jq 1.4.
Thanks.

**Comment by xuwang** [comment]
upgraded vbox to ubuntu-server-vivid and jq 1.4
