### ISSUE TITLE
[gen_certs] Error 2

### ISSUE THREAD

**Issue by dbethke** [xuwang/aws-linux-cluster#2]
vagrant@vagrant-ubuntu-vivid-64:~/aws-linux-cluster$ aws configure --profile mycluster
AWS Access Key ID [***************_RPJQ]:
AWS Secret Access Key [**_*************UyIc]:
Default region name [us-east-1]:
Default output format [None]:
vagrant@vagrant-ubuntu-vivid-64:~/aws-linux-cluster$ make
Getting AWS account number...
# Generate tf provider

/home/vagrant/aws-linux-cluster/scripts/gen-provider.sh > /home/vagrant/aws-linux-cluster/build/provider.tf
# Generate default AMI ids

/home/vagrant/aws-linux-cluster/scripts/get-ami.sh > /home/vagrant/aws-linux-cluster/build/ami.tf

cp -rf /home/vagrant/aws-linux-cluster/resources/terraforms/module-vpc.tf /home/vagrant/aws-linux-cluster/build
cd /home/vagrant/aws-linux-cluster/build; terraform get -update;
Get: file:///home/vagrant/aws-linux-cluster/modules/iam (update)
Get: file:///home/vagrant/aws-linux-cluster/modules/s3 (update)
Get: file:///home/vagrant/aws-linux-cluster/modules/vpc (update)
cp -rf /home/vagrant/aws-linux-cluster/resources/terraforms/module-s3.tf /home/vagrant/aws-linux-cluster/build
cd /home/vagrant/aws-linux-cluster/build; terraform get -update;
Get: file:///home/vagrant/aws-linux-cluster/modules/iam (update)
Get: file:///home/vagrant/aws-linux-cluster/modules/s3 (update)
Get: file:///home/vagrant/aws-linux-cluster/modules/vpc (update)
cp -rf /home/vagrant/aws-linux-cluster/resources/terraforms/module-iam.tf /home/vagrant/aws-linux-cluster/build
cd /home/vagrant/aws-linux-cluster/build; terraform get -update;
Get: file:///home/vagrant/aws-linux-cluster/modules/iam (update)
Get: file:///home/vagrant/aws-linux-cluster/modules/s3 (update)
Get: file:///home/vagrant/aws-linux-cluster/modules/vpc (update)
make[1]: Entering directory '/home/vagrant/aws-linux-cluster/build/certs'
echo "creating rootCA-key.pem and rootCA.pem ..."
creating rootCA-key.pem and rootCA.pem ...
openssl req -x509 -new -nodes -days 9999 -config rootCA.cnf -out rootCA.pem
Generating a 2048 bit RSA private key
...+++
.........................+++
## writing new private key to 'rootCA-key.pem'

chmod 600 _.pem
echo "creating the etcd-key.pem and etcd.csr...."
creating the etcd-key.pem and etcd.csr....
openssl req -new -out etcd.csr -config etcd.cnf
error on line -1 of etcd.cnf
140117452707472:error:02001002:system library:fopen:No such file or directory:bss_file.c:169:fopen('etcd.cnf','rb')
140117452707472:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:172:
140117452707472:error:0E078072:configuration file routines:DEF_LOAD:no such file:conf_def.c:197:
Makefile:24: recipe for target '/home/vagrant/aws-linux-cluster/build/certs//etcd.pem' failed
make[1]: *_\* [/home/vagrant/aws-linux-cluster/build/certs//etcd.pem] Error 1
make[1]: Leaving directory '/home/vagrant/aws-linux-cluster/build/certs'
resources/makefiles/init.mk:40: recipe for target 'gen_certs' failed
make: **\* [gen_certs] Error 2

**Comment by xuwang** [comment]
Fixed the bug by removing make target of generating etcd certs  (etcd certs has no use for this cluster).
